### ISSUE TITLE
Replace Family Name

### ISSUE THREAD

**Issue by napperley** [napperley/kotlin#1]
Currently in the Kotlin fork a new family called `BARE_METAL` has been defined in **Family.kt**. This name is very vague and doesn't accurately reflect on what the family is. This issue will be conducted as a poll to determine the replacement family name. Below are the replacement names being considered:

1. **ARM32_BARE_METAL**
2. **ARM32_EMBEDDED**
3. **ARM32_MICRO_CONTROLLER**

**Comment by chris-hatton** [comment]
Assuming there is no intermediary OS/RTOS layer that you're proposing to include, then I think the term 'Bare Metal' is well understood to mean that all resource management has to be undertaken by the language-compiled code.

I find the term 'Embedded' to be broader than this; sometimes even used for situations where a SoC is running full-blown Linux; just in a headless/industrial control scenario.

Considering the above `ARM32_BARE_METAL` gets my vote.

As for the `ARM32_` prefix - are you planning for general ARM32 support or targeting Rasperry Pi Nano (RP2040)? 
Consider `RP2040_BARE_METAL` if the latter?

_Disclaimer: Not an embedded software professional; just the proverbial 2c of a Kotlin fanatic and hardware hobbyist._

**Comment by LouisCAD** [comment]
I like `BARE_METAL`, plus it doesn't restrict the CPU bit width.

**Comment by napperley** [comment]
Sticking with the current name (**Bare Metal**) since it accurately reflects what is being targeted, and the **Architecture** enum covers bit width already.
